name: yacht_rental
description: Aplikacja wypożyczania jachtów

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  flutter_svg: ^2.0.9
  http: ^1.1.2
  qr_code_scanner: ^1.0.1
  webview_flutter: ^2.0.0
  crypto: ^3.0.3
  xml: ^6.5.0
  mysql1: ^0.20.0
  provider: ^6.1.1
  path_provider: ^2.1.1
  intl: ^0.18.0
  email_validator: ^2.1.17
  camera: ^0.10.5+6
  ftpconnect: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: Alata
      fonts:
        - asset: fonts/Alata-Regular.ttf

  uses-material-design: true

  assets:
    - assets/
